version: '3.1'

services:
  app:
    container_name: faesa-app
    build: .
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: php -S 0.0.0.0:81 -t /var/www/
    ports:
      - "81:81"
    links:
      - db
    environment:
      APP_ENV: local
      APP_NAME: faesa
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: php
      DB_USERNAME: php
      DB_PASSWORD: secret

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=php
      - PMA_PASSWORD=secret

  db:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: php
      MYSQL_USER: php
      MYSQL_PASSWORD: secret

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./portainer:/data"
    restart: unless-stopped